SET SQLBLANKLINES ON
PROMPT create table 'PROJECT_ALIAS'
CREATE TABLE PROJECT_ALIAS 
(
  ID NUMBER NOT NULL 
, PROJECT_ID NUMBER NOT NULL 
, ALIAS VARCHAR2(256) 
, DATE_CREATED DATE NOT NULL 
, CREATED_BY VARCHAR2(40) NOT NULL 
, LAST_UPDATED DATE NOT NULL 
, UPDATED_BY VARCHAR2(40) NOT NULL 
, CONSTRAINT PROJECT_ALIAS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

PROMPT alter table 'FORM'
ALTER TABLE FORM 
ADD (VERSION_NUMBER NUMBER );

PROMPT alter table 'FORM'
ALTER TABLE FORM 
ADD (DEPRICATED_DATE DATE );

PROMPT alter table 'NOTE'
ALTER TABLE NOTE 
ADD (DOCUMENT_REFERENCE_URL VARCHAR2(4000) );

PROMPT alter table 'ESA_USER'
ALTER TABLE ESA_USER  
MODIFY (PARTY_ID NULL);

PROMPT alter table 'ATTACHMENT'
ALTER TABLE ATTACHMENT MOVE;

PROMPT alter table 'PROJECT_ALIAS'
ALTER TABLE PROJECT_ALIAS
ADD CONSTRAINT PROJECT_ALIAS_FK FOREIGN KEY
(
  PROJECT_ID 
)
REFERENCES PROJECT
(
  ID 
)
ENABLE;

COMMENT ON COLUMN NOTE.DOCUMENT_REFERENCE_URL IS 'This is to proide a url reference to a document to support the note.';

PROMPT create sequence 'PROJECT_ALIAS_SEQ'
CREATE SEQUENCE PROJECT_ALIAS_SEQ NOCACHE;
