SET SQLBLANKLINES ON

PROMPT create table 'PROJECT_ARCHITECT'
CREATE TABLE PROJECT_ARCHITECT 
(
  ID NUMBER NOT NULL 
, PARTY_ID NUMBER NOT NULL 
, PROJECT_ID NUMBER NOT NULL 
, DATE_CREATED DATE NOT NULL 
, CREATED_BY VARCHAR2(40) NOT NULL 
, LAST_UPDATED DATE NOT NULL 
, UPDATED_BY VARCHAR2(40) NOT NULL 
, CONSTRAINT PROJECT_ARCHITECT_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE SEQUENCE PROJECT_ARCHITECT_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;

PROMPT migrating Architect to Project relationship
INSERT INTO PROJECT_ARCHITECT 
( ID,
  PARTY_ID,
  PROJECT_ID,
  DATE_CREATED,
  CREATED_BY,
  LAST_UPDATED,
  UPDATED_BY)
(SELECT
  PROJECT_ARCHITECT_SEQ.NEXTVAL,
  ARCHITECT_PARTY_ID,
  ID,
  DATE_CREATED,
  CREATED_BY,
  LAST_UPDATED,
  UPDATED_BY
FROM PROJECT
WHERE ARCHITECT_PARTY_ID IS NOT NULL);

COMMIT;

PROMPT alter table 'PROJECT'
ALTER TABLE PROJECT 
DROP CONSTRAINT ARCHITECT_PARTY_FK;

PROMPT alter table 'PROJECT'
ALTER TABLE PROJECT 
DROP COLUMN ARCHITECT_PARTY_ID;

PROMPT alter table 'ESA_USER'
ALTER TABLE ESA_USER 
ADD (PARTY_ID NUMBER );

PROMPT alter table 'ESA_USER'
ALTER TABLE ESA_USER
ADD CONSTRAINT ESA_USER_PARTY_FK FOREIGN KEY
(
  PARTY_ID 
)
REFERENCES PARTY
(
  ID 
)
ENABLE;

PROMPT alter table 'PROJECT_ARCHITECT'
ALTER TABLE PROJECT_ARCHITECT
ADD CONSTRAINT ARCHITECT_PROJECTS_FK FOREIGN KEY
(
  PARTY_ID 
)
REFERENCES PARTY
(
  ID 
)
ENABLE;

PROMPT alter table 'PROJECT_ARCHITECT'
ALTER TABLE PROJECT_ARCHITECT
ADD CONSTRAINT PROJECT_ARCHITECTS_FK FOREIGN KEY
(
  PROJECT_ID 
)
REFERENCES PROJECT
(
  ID 
)
ENABLE;

COMMENT ON COLUMN ESA_USER.PARTY_ID IS 'The person associated with the user account.';
