SET SQLBLANKLINES ON
PROMPT create table 'EXTERNAL_PROJECT_NUMBER'
CREATE TABLE EXTERNAL_PROJECT_NUMBER 
(
  ID NUMBER NOT NULL 
, VALUE VARCHAR2(64) NOT NULL 
, SOURCE_SYSTEM VARCHAR2(40) NOT NULL 
, PROJECT_ID NUMBER 
, DATE_CREATED DATE NOT NULL 
, CREATED_BY VARCHAR2(40) NOT NULL 
, LAST_UPDATED DATE NOT NULL 
, UPDATED_BY VARCHAR2(40) NOT NULL 
, CONSTRAINT EXTERNAL_PROJECT_NUMBERS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

PROMPT alter table 'EXTERNAL_PROJECT_NUMBER'
ALTER TABLE EXTERNAL_PROJECT_NUMBER
ADD CONSTRAINT EXTERNAL_PROJECT_NUMBER_FK FOREIGN KEY
(
  PROJECT_ID 
)
REFERENCES PROJECT
(
  ID 
)
ENABLE;

COMMENT ON COLUMN EXTERNAL_PROJECT_NUMBER.SOURCE_SYSTEM IS 'The source system identifying where the external project number is defined.  This is populated using a lookup value.';

PROMPT create sequence 'EXTERNAL_PROJECT_NUMBER_SEQ'
CREATE SEQUENCE EXTERNAL_PROJECT_NUMBER_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;

UPDATE CONFIGURATION_PARAMETER SET VALUE='1.5'
WHERE NAME='database.version';

COMMIT;
