REM INSERTING into CONFIGURATION_PARAMETER
Insert into CONFIGURATION_PARAMETER (ID,NAME,VALUE,CREATION_DATE,CREATED_BY,UPDATE_DATE,UPDATED_BY) values (1,'database.version','1.0',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad');
