SET SQLBLANKLINES ON
PROMPT create table 'ESA_ROLE'
CREATE TABLE ESA.ESA_ROLE 
(
  ID NUMBER NOT NULL 
, AUTHORITY VARCHAR2(1024) 
, VERSION NUMBER(19,0)
, CONSTRAINT ESA_ROLE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
, CONSTRAINT ESA_ROLE_AUTHORITY_UK UNIQUE ( AUTHORITY ) ENABLE
);

PROMPT create table 'ESA_USER'
CREATE TABLE ESA.ESA_USER
(
  ID NUMBER NOT NULL 
, USERNAME VARCHAR2(1024) NOT NULL
, PASSWORD VARCHAR2(1024) NOT NULL
, ENABLED NUMBER(1,0) DEFAULT 0
, ACCOUNT_EXPIRED NUMBER(1,0) DEFAULT 0
, ACCOUNT_LOCKED NUMBER(1,0) DEFAULT 0
, PASSWORD_EXPIRED NUMBER(1,0) DEFAULT 0
, VERSION NUMBER(19,0)
, CONSTRAINT USER_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
, CONSTRAINT USER_USERNAME_UK UNIQUE ( USERNAME ) ENABLE
);

PROMPT create table 'ESA_USER_ESA_ROLE'
CREATE TABLE ESA.ESA_USER_ESA_ROLE
(
  ESA_USER_ID NUMBER NOT NULL 
, ESA_ROLE_ID NUMBER NOT NULL
, CONSTRAINT ESA_USER_ESA_ROLE_PK PRIMARY KEY 
  (
    ESA_USER_ID, ESA_ROLE_ID
  )
  ENABLE 
, CONSTRAINT ESA_USER_ESA_ROLE_USR_FK FOREIGN KEY ( ESA_USER_ID ) REFERENCES ESA.ESA_USER (ID) ENABLE
, CONSTRAINT ESA_USER_ESA_ROLE_RLE_FK FOREIGN KEY ( ESA_ROLE_ID ) REFERENCES ESA.ESA_ROLE (ID) ENABLE
);

PROMPT create table 'REGISTRATION_CODE'
CREATE TABLE ESA.REGISTRATION_CODE
(
  ID NUMBER(19,0) NOT NULL 
, TOKEN VARCHAR(255 CHAR) NOT NULL
, DATE_CREATED TIMESTAMP (6) NOT NULL 
, USERNAME VARCHAR2(255 CHAR) NOT NULL
, CONSTRAINT REGISTRATION_CODE_PK PRIMARY KEY 
  (
    ID
  )
  ENABLE 
);

PROMPT create table 'SPRING_SECURITY_EVENT'
CREATE TABLE ESA.SPRING_SECURITY_EVENT
(
  ID NUMBER(19,0) NOT NULL 
, DATE_CREATED TIMESTAMP (6) NOT NULL 
, EVENT_NAME VARCHAR2(255 CHAR) NOT NULL
, REMOTE_ADDRESS VARCHAR2(255 CHAR) NOT NULL
, SESSION_ID VARCHAR2(255 CHAR)
, USERNAME VARCHAR2(255 CHAR)
, CONSTRAINT SPRING_SECURITY_EVENT_PK PRIMARY KEY 
  (
    ID
  )
  ENABLE 
);

PROMPT create sequence 'ESA_ROLE_SEQ'
CREATE SEQUENCE ESA.ESA_ROLE_SEQ NOCACHE;

PROMPT create sequence 'ESA_USER_SEQ'
CREATE SEQUENCE ESA.ESA_USER_SEQ NOCACHE;

PROMPT create sequence 'ESA_USER_ESA_ROLE_SEQ'
CREATE SEQUENCE ESA.ESA_USER_ESA_ROLE_SEQ NOCACHE;

PROMPT create sequence 'SPRING_SECURITY_EVENT_SEQ'
CREATE SEQUENCE ESA.SPRING_SECURITY_EVENT_SEQ NOCACHE;

PROMPT create sequence 'REGISTRATION_CODE_SEQ'
CREATE SEQUENCE ESA.REGISTRATION_CODE_SEQ NOCACHE;

REM the spring-security grails plug-in seems to depend on this
PROMPT create sequence 'HIBERNATE_SEQUENCE'
CREATE SEQUENCE ESA.HIBERNATE_SEQUENCE NOCACHE;