-- INSERTING into LOOKUP_LIST
INSERT INTO LOOKUP_LIST(ID, CREATED_BY, DATE_CREATED, DESCRIPTION, LAST_UPDATED, LIST_TYPE, NAME, PROMPT, SQL_STATEMENT, UPDATED_BY) VALUES (1, 'bulkLoad', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'This is a list of all the facilities at intermountain', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'fixed', 'FacilityList', 'Facility List', null, 'bulkLoad');
INSERT INTO LOOKUP_LIST(ID, CREATED_BY, DATE_CREATED, DESCRIPTION, LAST_UPDATED, LIST_TYPE, NAME, PROMPT, SQL_STATEMENT, UPDATED_BY) VALUES (2, 'bulkLoad', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'Yes or No response', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'fixed', 'YesNo', 'Yes/No', null, 'bulkLoad');
INSERT INTO LOOKUP_LIST(ID, CREATED_BY, DATE_CREATED, DESCRIPTION, LAST_UPDATED, LIST_TYPE, NAME, PROMPT, SQL_STATEMENT, UPDATED_BY) VALUES (3, 'bulkLoad', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'List of all current standards defined by EISA', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'sql', 'StandardsList', 'Standards List', 'select id value, name display from item where standard=''Y''', 'bulkLoad');
INSERT INTO LOOKUP_LIST(ID, CREATED_BY, DATE_CREATED, DESCRIPTION, LAST_UPDATED, LIST_TYPE, NAME, PROMPT, SQL_STATEMENT, UPDATED_BY) VALUES (4, 'bulkLoad', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'List of the types of company data', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'fixed', 'CompanyDataTypes', 'Company Data Types', null, 'bulkLoad');
INSERT INTO LOOKUP_LIST(ID, CREATED_BY, DATE_CREATED, DESCRIPTION, LAST_UPDATED, LIST_TYPE, NAME, PROMPT, SQL_STATEMENT, UPDATED_BY) VALUES (5, 'bulkLoad', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'List of the types of patient data', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'fixed', 'PatientDataTypes', 'Patient Data Types', null, 'bulkLoad');
INSERT INTO LOOKUP_LIST(ID, CREATED_BY, DATE_CREATED, DESCRIPTION, LAST_UPDATED, LIST_TYPE, NAME, PROMPT, SQL_STATEMENT, UPDATED_BY) VALUES (6, 'bulkLoad', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'List of devices or systems application can be installed', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'fixed', 'ApplicationInstalledOn', 'Application Installed On', null, 'bulkLoad');
INSERT INTO LOOKUP_LIST(ID, CREATED_BY, DATE_CREATED, DESCRIPTION, LAST_UPDATED, LIST_TYPE, NAME, PROMPT, SQL_STATEMENT, UPDATED_BY) VALUES (7, 'bulkLoad', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'List of databases acceptable to Intermountain', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'fixed', 'ListOfValidDatabases', 'List of Valid Databases', null, 'bulkLoad');
INSERT INTO LOOKUP_LIST(ID, CREATED_BY, DATE_CREATED, DESCRIPTION, LAST_UPDATED, LIST_TYPE, NAME, PROMPT, SQL_STATEMENT, UPDATED_BY) VALUES (8, 'bulkLoad', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'List of hosting methods', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'fixed', 'ApplicationHostingMethods', 'Application Hosting', null, 'bulkLoad');
INSERT INTO LOOKUP_LIST(ID, CREATED_BY, DATE_CREATED, DESCRIPTION, LAST_UPDATED, LIST_TYPE, NAME, PROMPT, SQL_STATEMENT, UPDATED_BY) VALUES (9, 'bulkLoad', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'List of IS infrastructure and application technology', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'fixed', 'InfrastructureList', 'Infrastructure List', null, 'bulkLoad');
INSERT INTO LOOKUP_LIST(ID, CREATED_BY, DATE_CREATED, DESCRIPTION, LAST_UPDATED, LIST_TYPE, NAME, PROMPT, SQL_STATEMENT, UPDATED_BY) VALUES (10, 'bulkLoad', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'List of agreement types such as BAA, ACA and so on', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'fixed', 'AgreementTypes', 'Agreement Types', null, 'bulkLoad');
INSERT INTO LOOKUP_LIST(ID, CREATED_BY, DATE_CREATED, DESCRIPTION, LAST_UPDATED, LIST_TYPE, NAME, PROMPT, SQL_STATEMENT, UPDATED_BY) VALUES (11, 'bulkLoad', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'List of the various types of approvals that can be granted by EISA', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'fixed', 'EISAApprovalStatus', 'EISA Approval Status', null, 'bulkLoad');
INSERT INTO LOOKUP_LIST(ID, CREATED_BY, DATE_CREATED, DESCRIPTION, LAST_UPDATED, LIST_TYPE, NAME, PROMPT, SQL_STATEMENT, UPDATED_BY) VALUES (12, 'bulkLoad', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'List of the various html form types: combo box, check box, text and so on', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'fixed', 'FormInputType', 'Form Input Type', null, 'bulkLoad');
INSERT INTO LOOKUP_LIST(ID, CREATED_BY, DATE_CREATED, DESCRIPTION, LAST_UPDATED, LIST_TYPE, NAME, PROMPT, SQL_STATEMENT, UPDATED_BY) VALUES (13, 'bulkLoad', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'List of the different types of standards throughtout the organizatoin such as corporate, department and so on', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'fixed', 'ItemStandardType', 'Item Standard Type', null, 'bulkLoad');
INSERT INTO LOOKUP_LIST(ID, CREATED_BY, DATE_CREATED, DESCRIPTION, LAST_UPDATED, LIST_TYPE, NAME, PROMPT, SQL_STATEMENT, UPDATED_BY) VALUES (14, 'bulkLoad', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'List of the types of notes created for an item.', to_timestamp('15-OCT-12','DD-MON-RR HH.MI.SSXFF AM'), 'fixed', 'NoteType', 'Note Type', null, 'bulkLoad');              
