-- INSERTING into LOOKUP_LIST
Insert into LOOKUP_LIST (ID,NAME,PROMPT,DESCRIPTION,LIST_TYPE,SQL_STATEMENT,DATE_CREATED,CREATED_BY,LAST_UPDATED,UPDATED_BY) values (1,'FacilityList','Facility List','This is a list of all the facilities at intermountain','fixed',null,to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad');
Insert into LOOKUP_LIST (ID,NAME,PROMPT,DESCRIPTION,LIST_TYPE,SQL_STATEMENT,DATE_CREATED,CREATED_BY,LAST_UPDATED,UPDATED_BY) values (2,'YesNo','Yes/No','Yes or No response','fixed',null,to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad');
Insert into LOOKUP_LIST (ID,NAME,PROMPT,DESCRIPTION,LIST_TYPE,SQL_STATEMENT,DATE_CREATED,CREATED_BY,LAST_UPDATED,UPDATED_BY) values (3,'StandardsList','Standards List','List of all current standards defined by EISA','sql','select id value, name display from item where standard=''Y''',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad');
Insert into LOOKUP_LIST (ID,NAME,PROMPT,DESCRIPTION,LIST_TYPE,SQL_STATEMENT,DATE_CREATED,CREATED_BY,LAST_UPDATED,UPDATED_BY) values (4,'CompanyDataTypes','Company Data Types','List of the types of company data','fixed',null,to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad');
Insert into LOOKUP_LIST (ID,NAME,PROMPT,DESCRIPTION,LIST_TYPE,SQL_STATEMENT,DATE_CREATED,CREATED_BY,LAST_UPDATED,UPDATED_BY) values (5,'PatientDataTypes','Patient Data Types','List of the types of patient data','fixed',null,to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad');
Insert into LOOKUP_LIST (ID,NAME,PROMPT,DESCRIPTION,LIST_TYPE,SQL_STATEMENT,DATE_CREATED,CREATED_BY,LAST_UPDATED,UPDATED_BY) values (6,'ApplicationInstalledOn','Application Installed On','List of places where the application can be installed','fixed',null,to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad');
Insert into LOOKUP_LIST (ID,NAME,PROMPT,DESCRIPTION,LIST_TYPE,SQL_STATEMENT,DATE_CREATED,CREATED_BY,LAST_UPDATED,UPDATED_BY) values (7,'ListOfValidDatabases','List of Valid Databases','List of databases acceptable to Intermountain','fixed',null,to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad');
Insert into LOOKUP_LIST (ID,NAME,PROMPT,DESCRIPTION,LIST_TYPE,SQL_STATEMENT,DATE_CREATED,CREATED_BY,LAST_UPDATED,UPDATED_BY) values (8,'ApplicationHostingMethods','Application Hosting','List of hosting methods','fixed',null,to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad');
Insert into LOOKUP_LIST (ID,NAME,PROMPT,DESCRIPTION,LIST_TYPE,SQL_STATEMENT,DATE_CREATED,CREATED_BY,LAST_UPDATED,UPDATED_BY) values (9,'InfrastructureList','Infrastructure List','List of IS infrastructure and application technology','fixed',null,to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad');
Insert into LOOKUP_LIST (ID,NAME,PROMPT,DESCRIPTION,LIST_TYPE,SQL_STATEMENT,DATE_CREATED,CREATED_BY,LAST_UPDATED,UPDATED_BY) values (10,'AgreementTypes','Agreement Types','List of agreement types such as BAA, ACA and so on','fixed',null,to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad');
Insert into LOOKUP_LIST (ID,NAME,PROMPT,DESCRIPTION,LIST_TYPE,SQL_STATEMENT,DATE_CREATED,CREATED_BY,LAST_UPDATED,UPDATED_BY) values (11,'EISAApprovalStatus','EISA Approval Status','List of the various types of approvals that can be granted by EISA','fixed',null,to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad');
Insert into LOOKUP_LIST (ID,NAME,PROMPT,DESCRIPTION,LIST_TYPE,SQL_STATEMENT,DATE_CREATED,CREATED_BY,LAST_UPDATED,UPDATED_BY) values (12,'FormInputType','Form Input Type','List of the various html form types: combo box, check box, text and so on','fixed',null,to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad');
Insert into LOOKUP_LIST (ID,NAME,PROMPT,DESCRIPTION,LIST_TYPE,SQL_STATEMENT,DATE_CREATED,CREATED_BY,LAST_UPDATED,UPDATED_BY) values (13,'ItemStandardType','Item Standard Type','List of the different types of standards throughtout the organizatoin such as corporate, department and so on','fixed',null,to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad');
Insert into LOOKUP_LIST (ID,NAME,PROMPT,DESCRIPTION,LIST_TYPE,SQL_STATEMENT,DATE_CREATED,CREATED_BY,LAST_UPDATED,UPDATED_BY) values (14,'NoteType','Note Type','List of the types of notes created for an item.','fixed',null,to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad',to_timestamp('13-AUG-12','DD-MON-RR HH.MI.SSXFF AM'),'bulkLoad');
