/*
 * To change this template comment, edit OracleESA.TEMPLATES.TEMPLATE_TRIGGER1
 */
CREATE OR REPLACE TRIGGER TEMPLATE_TRIGGER1 
BEFORE INSERT OR UPDATE OR DELETE ON TEMPLATES.TEMPLATE_TABLE1 
BEGIN
  NULL;
END;
/
